export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(git nvm go rust sdkman)

# Tilix
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi

source $ZSH/oh-my-zsh.sh

