export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(git nvm go rust sdkman)

# Tilix
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi

# ssh-agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

source $ZSH/oh-my-zsh.sh

